image: node:latest

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    # should be a build artifact, but upload would take ~10min
    - node_modules/

install:
  stage: build

  before_script:
    # setup authentication via https URLs
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.inria.fr".insteadOf "ssh://git@gitlab.inria.fr"

  script:
    # npm run as root: add --unsafe-perm to prevent cryptic blocking warning (…):
    # npm WARN lifecycle concordant-crdtlib@1.0.0~prepack: cannot run in wd concordant-crdtlib@1.0.0~prepack
    #     <...> (wd=/builds/concordant/software/c-labbook/.npm/_cacache/tmp/git-clone-74e8bbe3)
    - npm ci --cache .npm --prefer-offline --unsafe-perm

test:
  stage: test
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # pull only (test don't modify node_modules)
    policy: pull
  script:
    # ignore react-scripts rejecting newer eslint
    - SKIP_PREFLIGHT_CHECK=true npm run coverage
  # regex for coverage measure
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
